name: format

on: [push, pull_request]

jobs:
  usort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install usort.
        run: |
          pip install usort
      - name: Run usort check.
        run: |
          usort check .
  # TODO: make formatting with ruff consistent across internal and open-source code.
  # ruff:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: astral-sh/ruff-action@v1
  #       with:
  #         args: "format --check"
